# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: comet_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypostgres
      POSTGRES_DB: CoMet_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
